Alias `killp` to fuzzily kill by port

diff --git a/functions/_fzf_functions b/functions/_fzf_functions
--- a/functions/_fzf_functions
+++ b/functions/_fzf_functions
@@ -47,6 +47,41 @@ fzf-modified-history-widget() {
   return $ret
 }
 
+# <<<< run @ shell or aliased >>>>
+
+fzf_kill_by_port() {
+  local port="$1"
+
+  [[ -z $port ]] && {
+    echo 'No port given, aborting'
+    return 1
+  }
+
+  # TODO: switch to alternate `&>/dev/null` in future
+  # ref - https://askubuntu.com/questions/474556/hiding-output-of-a-command
+  lsof -i :"$port" > /dev/null 2>&1 || {
+    echo 'Port has no attached processes, aborting'
+    return 1
+  }
+
+  # `sed '1d'` removes header line
+  # `sed -nE ...` filters out only PIDs
+  kill -9 $(\
+    lsof -i :"$port" \
+    | sed '1d' \
+    | fzf -m \
+    | sed -nE 's/^[[:alnum:]]+[[:space:]]+([[:digit:]]+)[[:space:]]+.*$/\1/p' \
+  )
+
+  # avoid race condition between next `lsof` call and processes shutting down
+  sleep 0.01
+
+  lsof -i :"$port" > /dev/null 2>&1 && {
+    echo "Remaining attached processes:\n"
+    lsof -i:"$port"
+  }
+}
+
 # fuzzy select files containing given term
 # TODO: see if search term can be changed interactively
 #
