Clean up conditionals

diff --git a/functions/extract b/functions/extract
--- a/functions/extract
+++ b/functions/extract
@@ -8,24 +8,25 @@
 # ref - http://nparikh.org/notes/zshrc.txt
 file="$1"
 
-if [ -f "$file" ]; then
-  case "$file" in
-    *.tar.bz2) tar -jxvf "$file" ;;
-    *.tar.gz) tar -zxvf "$file" ;;
-    *.bz2) bunzip2 "$file" ;;
-    *.dmg) hdiutil mount "$file" ;;
-    *.gz) gunzip "$file" ;;
-    *.tar) tar -xvf "$file" ;;
-    *.tbz2) tar -jxvf "$file" ;;
-    *.tgz) tar -zxvf "$file" ;;
-    *.zip) unzip "$file" ;;
-    *.ZIP) unzip "$file" ;;
-    *.pax) pax -r < "$file" ;;
-    *.pax.Z) uncompress "$file" --stdout | pax -r ;;
-    *.rar) unrar x "$file" ;;
-    *.Z) uncompress "$file" ;;
-    *) echo "'$file' cannot be extracted/mounted via extract()" ;;
-  esac
-else
+[ -f "$file" ] || {
   echo "'$file' is not a valid file"
-fi
+  exit 1
+}
+
+case "$file" in
+  *.tar.bz2) tar -jxvf "$file" ;;
+  *.tar.gz) tar -zxvf "$file" ;;
+  *.bz2) bunzip2 "$file" ;;
+  *.dmg) hdiutil mount "$file" ;;
+  *.gz) gunzip "$file" ;;
+  *.tar) tar -xvf "$file" ;;
+  *.tbz2) tar -jxvf "$file" ;;
+  *.tgz) tar -zxvf "$file" ;;
+  *.zip) unzip "$file" ;;
+  *.ZIP) unzip "$file" ;;
+  *.pax) pax -r < "$file" ;;
+  *.pax.Z) uncompress "$file" --stdout | pax -r ;;
+  *.rar) unrar x "$file" ;;
+  *.Z) uncompress "$file" ;;
+  *) echo "'$file' cannot be extracted/mounted via extract()" ;;
+esac
