Refactor `setup_desktop_apps`

diff --git a/gui/setup/setup_desktop_apps b/gui/setup/setup_desktop_apps
--- a/gui/setup/setup_desktop_apps
+++ b/gui/setup/setup_desktop_apps
@@ -6,48 +6,68 @@ source "${BASH_SOURCE%/*}/../../infra/setup/check_dotfiles_variable.sh"
 
 source "$DOTFILES/infra/scripts/prompts.sh"
 
-[[ $SHOULD_SETUP_DESKTOP_APPS == false ]] && exit 0
+main() {
+  parse_input "$@"
 
-command -v brew > /dev/null || {
-  # shellcheck disable=SC2016
-  echo 'Setting up desktop apps requires `brew` to be installed'
-  exit 1
-}
+  [[ $SHOULD_SETUP_DESKTOP_APPS == false ]] && exit 0
 
-"$DOTFILES/infra/scripts/is_macos.sh" || {
-  echo 'Desktop app setup only supported for macOS currently'
-  exit 1
-}
-
-# << casks setup >>
-[[ $SHOULD_SETUP_DESKTOP_APPS == true ]] || {
-  user "set up desktop apps? (casks listed in $DOTFILES/gui/apps/Brewfile)?\
-   (y/any other key)"
-
-  read -r -s -n 1 maybe_continue < /dev/tty
-
-  [[ "$maybe_continue" != 'y' ]] && {
-    info "skipping cask setup"
-    exit 0
+  command -v brew > /dev/null || {
+    # shellcheck disable=SC2016
+    echo 'Setting up desktop apps requires `brew` to be installed'
+    exit 1
   }
+
+  "$DOTFILES/infra/scripts/is_macos.sh" || {
+    echo 'Desktop app setup only supported for macOS currently'
+    exit 1
+  }
+
+  # << casks setup >>
+  [[ $SHOULD_SETUP_DESKTOP_APPS == true ]] || {
+    user "set up desktop apps? (casks listed in $DOTFILES/gui/apps/Brewfile)?\
+     (y/any other key)"
+
+    read -r -s -n 1 maybe_continue < /dev/tty
+
+    [[ "$maybe_continue" != 'y' ]] && {
+      info "skipping cask setup"
+      exit 0
+    }
+  }
+
+  echo 'setting up desktop apps (casks)'
+
+  cd "$DOTFILES/gui/apps" || {
+    # shellcheck disable=SC2016
+    printf 'failed to `cd` to "%s/gui/apps", `brew bundle` not run' "$DOTFILES"
+    exit 1
+  }
+
+  brew bundle
+  success "set up casks"
+  # << end casks setup >>
+
+  command -v mas > /dev/null || brew install "mas"
+
+  # this line will error unless you have purchased Super Easy Timer. Delete or
+  # comment this line out to avoid errors.
+  # TODO: check for apple account first?
+  # ref - https://github.com/mas-cli/mas
+  mas install 1353137878 # Super Easy Timer
 }
 
-echo 'setting up desktop apps (casks)'
-
-cd "$DOTFILES/gui/apps" || {
-  # shellcheck disable=SC2016
-  printf 'failed to `cd` to "%s/gui/apps", `brew bundle` not run' "$DOTFILES"
-  exit 1
+# handle any arguments/flags
+parse_input() {
+  for opt in "$@"; do
+    case $opt in
+      --skip-desktop-apps)
+        export SHOULD_SETUP_DESKTOP_APPS=false
+        ;;
+      --setup-desktop-apps)
+        export SHOULD_SETUP_DESKTOP_APPS=true
+        ;;
+    esac
+  done
 }
 
-brew bundle
-success "set up casks"
-# << end casks setup >>
-
-command -v mas > /dev/null || brew install "mas"
-
-# this line will error unless you have purchased Super Easy Timer. Delete or
-# comment this line out to avoid errors.
-# TODO: check for apple account first?
-# ref - https://github.com/mas-cli/mas
-mas install 1353137878 # Super Easy Timer
+main "$@"
