Extract components detailed by scheme

diff --git a/setup/bin/symlink b/setup/bin/symlink
--- a/setup/bin/symlink
+++ b/setup/bin/symlink
@@ -220,6 +220,10 @@
 # - allow symlinking inner directory of outer created directory? Any use case?
 # - allow truly arbitrary paths? not just off of `~`? would require sudo
 
+source $DOTFILES/setup/lib/prompts.sh
+source $DOTFILES/setup/lib/util.sh
+
+_symlink_regex="^(([-._a-zA-Z]+~)*)([-._a-zA-Z]+)\.symlink(\.([_d]{1,2}))?$"
 
 symlink () {
   info "symlinking dotfiles according to scheme in $DOTFILES/setup/bin/symlink"
@@ -227,22 +231,124 @@ symlink () {
   local overwrite_all=false backup_all=false skip_all=false
 
   # write all files ending in .symlink
-  for src in $(find -H "$DOTFILES" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
+  for src in \
+    $(find -H "$DOTFILES" -maxdepth 2 -name '*.symlink*' -not -path '*.git*')
   do
-    dst="$HOME/.$(basename "${src%.*}")"
-    link_file "$src" "$dst"
+    filename=$(basename $src)
+    [[ $filename =~ $_symlink_regex ]] && {
+      echo "valid - $filename"
+      _symlink_based_on_filename $filename $src
+    } || {
+      info "skipped symlinking file w/ invalid syntax - $filename";
+    }
   done
+}
 
-  for src in $DOTFILES/config/*
-  do
-    dst="$HOME/.config/$(basename $src)"
-    link_file "$src" "$dst"
-  done
+check_regex() {
+  _symlink_regex='^(([-._a-zA-Z]+~)*)([-._a-zA-Z]+)\.symlink(\.([_d]{1,2}))?$'
+
+  filename=$(basename $1)
+  [[ $filename =~ $_symlink_regex ]] && {
+    echo "valid - $filename"
+    _symlink_based_on_filename $filename $1
+  } || {
+    info "skipped symlinking file w/ invalid syntax - $filename";
+  }
+}
+
+_symlink_based_on_filename() {
+  local filename=$1 src=$2
+  local _path="" _name="" _direct=false _hidden=false
+
+  # extracts destination name and optional path from target filename
+  _extract_path
+  _extract_name
+
+  echo "path: $_path"
+  echo "name: $_name"
+
+  # extracts and checks values of each possible flag
+  _check_flags
+  echo "direct: $_direct"
+  echo "hidden: $_hidden"
+
+  # dst="$HOME/.$(basename "${src%.*}")"
+
+  # link_file $src $dst
+}
+
+# regex to apply in `$1`, string to apply to in `$2`
+# save/return in `_regex_matches`
+_apply_regex() {
+  # not using for conditional, solely to populate match array
+  [[ $2 =~ $1 ]]
+
+  # outer parens, `(...)`, ensure copying as array, not string
+  # TODO: more portable answer? currently defaulting to `BASH_REMATCH` if it
+  # exists. `match` is `zsh` version of same environment variable
+  _regex_matches=(${BASH_REMATCH[@]:-${match[@]}})
+}
+
+_extract_path() {
+  # path capture group @ _regex_matches[1] (if _regex_matches length 2 or
+  # greater)
+  local _path_regex='^(([-._a-zA-Z]+~)*).*'
+  _apply_regex $_path_regex $filename
+
+  # _regex_matches will only have length >= 2 if capture groups triggered,
+  # meaning we have path components
+  if [ "${#_regex_matches[@]}" -ge 2 ]; then
+    # split array on delimiter
+    # `local IFS='<delimiter>' scopes any interference w/ `IFS`
+    # `(<string>)` - parens trigger splitting `<string>` on `IFS` value
+    # ref - https://stackoverflow.com/questions/918886/how-do-i-split-a-string-on-a-delimiter-in-bash#tab-top
+    local IFS='~';
+    # outer path capture group @ index 1 (index 0 holds entire matched string)
+    path_components=(${_regex_matches[1]})
+
+    # join array back w/ `join_by` function (return value saved in `_joined`)
+    # `join_by` defined in $DOTFILES/setup/lib/util.sh
+    local _joined=""
+    join_by '/' "${path_components[@]}"
+    _path=$_joined
+  fi
+}
+
+_extract_name() {
+  # file/directory name capture group
+  local _name_regex='~?([-._a-zA-Z]+)\.symlink.*$';
+  _apply_regex $_name_regex $filename
+
+  # not using for conditional, solely to populate match array
+  [[ $filename =~ $_name_regex ]];
+  # outer parens, `(...)`, ensure copying as array, not string
+  local _regex_matches=(${BASH_REMATCH[@]:-${match[@]}});
+
+  # outer path capture group @ index 1 (index 0 holds entire matched string)
+  _name=${_regex_matches[1]};
+}
+
+_check_flags() {
+  # flags capture group @ _regex_matches[1] (if _regex_matches length 2)
+  local _flags_regex='^.*\.symlink(\.[_d]{1,2})?$';
+  _apply_regex $_flags_regex $filename
+
+  # _regex_matches will only have length 2 if capture groups triggered, meaning
+  # we have flags
+  if [ "${#_regex_matches[@]}" -eq 2 ]; then
+    local _flags=${_regex_matches[1]};
+
+    # check for substrings
+    # if `d` & `_` in `_flags`
+    # ref - https://stackoverflow.com/questions/229551/how-to-check-if-a-string-contains-a-substring-in-bash
+    [[ $_flags == *"d"* ]] && { _direct=true; }
+    [[ $_flags == *"_"* ]] && { _hidden=true; };
+  fi
 }
 
 # link single file between `src` & `dst`
 # takes user input (potentially modified by `<option>_all` flags defined in
-# calling scope
+# calling scope)
 #
 # Args:
 #   - src - source path
@@ -322,4 +428,6 @@ link_file () {
   fi
 }
 
-symlink
+# TODO: remove this
+echo 'remove me'
+check_regex $DOTFILES/config/one-one~two.two~file-name.extension.symlink.d
