nix: clean up setup script

diff --git a/infra/setup/bin/setup_nix b/infra/setup/bin/setup_nix
--- a/infra/setup/bin/setup_nix
+++ b/infra/setup/bin/setup_nix
@@ -8,15 +8,30 @@ source "${BASH_SOURCE%/*}/../check_dotfiles_variable.sh"
 source "$DOTFILES/infra/scripts/prompts.sh"
 
 main() {
-  local MAC_INSTALLATION_FLAGS
+  info 'setting up `nix` (manages these dotfiles)'
 
-  info 'setting up `nix` (package manager)'
+  setup_nix || exit 1
+
+  setup_home_manager || exit 1
+
+  success '`nix` (and various pieces) setup complete'
+}
+
+setup_nix() {
+  command -v nix-env > /dev/null && {
+    info 'skipping `nix` installation since `nix-env` is invokable'
+    return 0
+  }
 
   # macOS (as of Catalina) makes the root (`/`) read-only
   # `nix` can workaround this by creating a "synthetic" directory at `/nix` and
   # mounting a separate volume which holds the actual contents
-  # TODO: update docs/flesh out comments here
-  # PR docs - https://dgn9s9wft3u6a.cloudfront.net/store/4iwvbj92fc10yyxla50an3vghajikwbl-manual/manual.html#sect-macos-installation
+  #
+  # As the ref below points out, "unencrypted" is a bit of a misnomer. Any Mac
+  # with a T2 chip will still be encrypted at rest
+  #
+  # ref - https://nixos.org/nix/manual/#sect-macos-installation
+  local MAC_INSTALLATION_FLAGS
   "$DOTFILES/infra/scripts/is_macos.sh" && {
     MAC_INSTALLATION_FLAGS='--darwin-use-unencrypted-nix-store-volume'
   }
@@ -26,41 +41,59 @@ main() {
   # daemon?
   # TODO: explain why multiuser and differences w/ single-user install
   # https://nixos.org/nix/manual/#sect-multi-user-installation
-  command -v nix-env > /dev/null || {
-    sh <(curl -L https://nixos.org/nix/install) \
-      --daemon \
-      "$MAC_INSTALLATION_FLAGS"
-  }
+  sh <(curl -L https://nixos.org/nix/install) \
+    --daemon \
+    "$MAC_INSTALLATION_FLAGS"
 
-  # initialize `nix` for next steps
+  # initialize `nix` for next steps - same lines added to /etc/zshrc by installer
   if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
     # shellcheck disable=SC1091
     . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
   fi
 
   command -v nix-env > /dev/null || {
-    echo 'The `nix-env` binary is not available, installation may have errored.'
-    exit 1
+    fail "Nix installation finished but the \`nix-env\` binary is not available.
+ Please fix any issues and try again."
+    return 1
   }
 
-  # ref - https://github.com/rycee/home-manager#installation
-  # install home manager
+  success '`nix` installed'
+}
+
+setup_home_manager() {
+  command -v home-manager > /dev/null && {
+    info 'skipping `home-manager` installation since `home-manager` is invokable'
+    return 0
+  }
+
+  # install home manager - https://github.com/rycee/home-manager#installation
   nix-channel --add \
     https://github.com/rycee/home-manager/archive/master.tar.gz \
     home-manager
   nix-channel --update
 
   # make home-manager available (also done on each shell load in zshrc)
-  # ref - https://github.com/rycee/home-manager#installation
   export NIX_PATH=$HOME/.nix-defexpr/channels${NIX_PATH:+:}$NIX_PATH
 
   # install & create first generation
   nix-shell '<home-manager>' -A install
 
-  # TODO: do I need to `home-manager switch` here?
+  command -v home-manager > /dev/null || {
+    fail "\`home-manager\` installation finished but the \`home-manager\`
+ command is not invokable. Please fix any issues and try again."
+    return 1
+  }
+
+  # switch to home-manager config
+  home-manager switch || {
+    fail '`home-manager` setup failed on `home-manager switch`'
+    return 1
+  }
 
   # symlink home config
   ln -sf "$DOTFILES/nix/home.nix" "$HOME/.config/nixpkgs/home.nix"
+
+  success '`home-manager` setup complete'
 }
 
 main "$@"
