infra: refactor `setup_dotfiles`

diff --git a/infra/setup/setup_dotfiles b/infra/setup/setup_dotfiles
--- a/infra/setup/setup_dotfiles
+++ b/infra/setup/setup_dotfiles
@@ -8,45 +8,54 @@
 # shellcheck disable=SC1090
 source "${BASH_SOURCE%/*}/check_dotfiles_variable.sh"
 
-printf '\x1b[38;5;006mstarting dotfiles setup\x1b[0m\n\n'
+main() {
+  local teal_highlight clear_highlight
+  teal_highlight='\x1b[38;5;006m'
+  clear_highlight='\x1b[0m\n\n'
 
-# symlink config files to their correct locations
-# done early so that other installation steps can make use of these files (for
-# example, setting up home-manager for the first time in `setup_nix` requires
-# `$DOTFILES/nix/home.nix` to be symlinked appropriately)
-"$DOTFILES/infra/setup/bin/symlink"
+  printf "%bstarting dotfiles setup%b" "$teal_highlight" "$clear_highlight"
 
-# TODO: test if available for future setup steps
-"$DOTFILES/infra/setup/bin/setup_nix" || {
-  # shellcheck disable=SC2016
-  echo '`nix` installation failed.'
-  # shellcheck disable=SC2016
-  echo 'Try opening a new shell and rerunning `$DOTFILES/infra/setup/bin/setup_nix`'
-  exit 1
+  # symlink config files to their correct locations
+  # done early so that other installation steps can make use of these files (for
+  # example, setting up home-manager for the first time in `setup_nix` requires
+  # `$DOTFILES/nix/home.nix` to be symlinked appropriately)
+  "$DOTFILES/infra/setup/bin/symlink"
+
+  # TODO: test if available for future setup steps
+  "$DOTFILES/infra/setup/bin/setup_nix" || {
+    # shellcheck disable=SC2016
+    echo '`nix` installation failed.'
+    # shellcheck disable=SC2016
+    echo 'Try opening a new shell and rerunning `$DOTFILES/infra/setup/bin/setup_nix`'
+    exit 1
+  }
+
+  # generate user-specific gitconfig (name & email) @ `$HOME/.gitconfig.local`
+  "$DOTFILES/infra/setup/bin/setup_git_config" "$HOME/.gitconfig.local" --skip-existing
+
+  # set up our shell (`zsh`)
+  # this adds `zsh` to our allowed shells and sets it as the default. Then it
+  # loads `zsh` for the first time to install plugins & complete setup.
+  "$DOTFILES/infra/setup/bin/setup_zsh"
+
+  # load neovim for the first time to install plugins
+  "$DOTFILES/infra/setup/bin/setup_neovim"
+
+  # set up various pieces too small for their own files
+  # see the file in question for each piece
+  "$DOTFILES/infra/setup/bin/setup_bits_and_pieces"
+
+  # run after `$DOTFILES/infra/setup/bin/symlink` so that $DOTFILES/utilities/asdf/tool-versions is
+  # symlinked to `$HOME/.tool-versions`
+  "$DOTFILES/infra/setup/bin/setup_asdf"
+
+  # optionally set up work-specific config (confirms via user prompt)
+  "$DOTFILES/infra/setup/bin/setup_work"
+
+  printf "%bstarting new shell, happy coding!%b" "$teal_highlight" "$clear_highlight"
+  printf "%bsetup finished! 🎉%b" "$teal_highlight" "$clear_highlight"
+
+  zsh --interactive
 }
 
-# generate user-specific gitconfig (name & email) @ `$HOME/.gitconfig.local`
-"$DOTFILES/infra/setup/bin/setup_git_config" "$HOME/.gitconfig.local" --skip-existing
-
-# set up our shell (`zsh`)
-# this adds `zsh` to our allowed shells and sets it as the default. Then it
-# loads `zsh` for the first time to install plugins & complete setup.
-"$DOTFILES/infra/setup/bin/setup_zsh"
-
-# load neovim for the first time to install plugins
-"$DOTFILES/infra/setup/bin/setup_neovim"
-
-# set up various pieces too small for their own files
-# see the file in question for each piece
-"$DOTFILES/infra/setup/bin/setup_bits_and_pieces"
-
-# run after `$DOTFILES/infra/setup/bin/symlink` so that $DOTFILES/utilities/asdf/tool-versions is
-# symlinked to `$HOME/.tool-versions`
-"$DOTFILES/infra/setup/bin/setup_asdf"
-
-# optionally set up work-specific config (confirms via user prompt)
-"$DOTFILES/infra/setup/bin/setup_work"
-
-printf '\n\n\x1b[38;5;006msetup finished! \x1b[0m🎉\n'
-printf '\x1b[38;5;006mstarting new shell, happy coding\x1b[0m\n'
-zsh -i
+main "$@"
